package main

const adminHTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ConmeGOL - Administrador</title><style>
*{box-sizing:border-box}body{margin:0;background:#121212;color:#eee;font-family:Segoe UI,Arial,sans-serif}.wrap{max-width:1180px;margin:0 auto;padding:24px}.card{background:#1f1f1f;border:1px solid #2d2d2d;border-radius:14px;padding:20px}.login{max-width:460px;margin:9vh auto}.brand{font-size:22px;font-weight:700;color:#fff}.muted{color:#aaa;font-size:13px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.stack{display:grid;gap:10px}input,button{font:inherit;border-radius:8px;border:1px solid #3a3a3a;padding:10px 12px;background:#181818;color:#fff}input{min-width:160px}button{cursor:pointer;font-weight:600}button:hover{border-color:#38bdf8}.primary{background:#2563eb;border-color:#2563eb}.danger{background:#7f1d1d}.ok{background:#166534}.grid{overflow:auto;margin-top:16px}table{width:100%;border-collapse:collapse;min-width:1000px}th,td{text-align:left;padding:10px;border-bottom:1px solid #303030;font-size:13px}th{color:#aaa}.pending{color:#facc15}.approved{color:#4ade80}.rejected,.revoked,.expired{color:#f87171}.top{display:flex;justify-content:space-between;align-items:center;gap:10px}.hidden{display:none}.tabs{display:flex;gap:8px;margin:16px 0}.tabs button.active{border-color:#38bdf8;color:#38bdf8}#msg,#loginmsg,#setupmsg{min-height:22px;margin-top:10px;color:#38bdf8}.adminlist{display:grid;gap:8px;margin-top:12px}.adminitem{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px;border:1px solid #333;border-radius:8px}</style></head><body>
<div id="setup" class="wrap hidden"><div class="card login"><div class="brand">ConmeGOL Patch</div><p class="muted">Configuración inicial</p><div class="stack"><input id="setupcode" type="password" placeholder="Código de instalación"><input id="setupemail" type="email" placeholder="Correo"><input id="setuppass" type="password" placeholder="Contraseña (mínimo 10 caracteres)"><button class="primary" onclick="bootstrap()">CREAR ADMINISTRADOR</button></div><div id="setupmsg" class="muted"></div></div></div>
<div id="login" class="wrap hidden"><div class="card login"><div class="brand">ConmeGOL Patch</div><p class="muted">Administrador de licencias</p><div class="stack"><input id="email" type="email" placeholder="Correo" autocomplete="username"><input id="pass" type="password" placeholder="Contraseña" autocomplete="current-password"><button class="primary" onclick="login()">ENTRAR</button></div><div id="loginmsg" class="muted"></div></div></div>
<div id="panel" class="wrap hidden"><div class="card"><div class="top"><div><div class="brand">ConmeGOL Patch</div><div id="who" class="muted"></div></div><div class="row"><button onclick="refresh()">ACTUALIZAR</button><button onclick="logout()">SALIR</button></div></div><div class="tabs"><button id="tabclients" class="active" onclick="tab('clients')">CLIENTES</button><button id="tabadmins" onclick="tab('admins')">ADMINISTRADORES</button></div><div id="msg"></div>
<div id="clients"><div class="row"><label class="muted">Días <input id="days" type="number" min="0" max="3650" value="90" style="width:90px"></label><span class="muted">0 = permanente</span></div><div class="grid"><table><thead><tr><th>Nombre</th><th>Correo</th><th>PC</th><th>Estado</th><th>Solicitud</th><th>Última conexión</th><th>Vence</th><th>Acciones</th></tr></thead><tbody id="rows"></tbody></table></div></div>
<div id="admins" class="hidden"><p class="muted">Hasta 5 administradores iguales. No existe propietario fijo. No se puede eliminar el último administrador.</p><div class="row"><input id="newadminemail" type="email" placeholder="Correo nuevo"><input id="newadminpass" type="password" placeholder="Contraseña temporal"><button class="primary" onclick="addAdmin()">AGREGAR</button></div><div id="adminlist" class="adminlist"></div><hr style="border-color:#333;margin:20px 0"><div class="row"><input id="curpass" type="password" placeholder="Contraseña actual"><input id="newpass" type="password" placeholder="Nueva contraseña"><button onclick="changePassword()">CAMBIAR MI CONTRASEÑA</button></div></div>
</div></div>
<script>
let token=sessionStorage.getItem('cgp_admin_token')||'';let myEmail=sessionStorage.getItem('cgp_admin_email')||'';let timer=0;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(t){if(!t)return '-';return new Date(t*1000).toLocaleString()}
async function api(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(token)opt.headers.Authorization='Bearer '+token;let r=await fetch(path,opt);let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
async function init(){try{let j=await api('/v1/admin/bootstrap/status');if(j.setup_needed){show('setup')}else if(token){showPanel()}else{show('login')}}catch(e){show('login')}}function show(id){for(let x of ['setup','login','panel'])document.getElementById(x).classList.add('hidden');document.getElementById(id).classList.remove('hidden')}
async function bootstrap(){setupmsg.textContent='Creando...';try{await api('/v1/admin/bootstrap',{method:'POST',body:JSON.stringify({setup_code:setupcode.value.trim(),email:setupemail.value.trim(),password:setuppass.value})});setupmsg.textContent='Administrador creado. Ingresá con tu correo y contraseña.';setTimeout(()=>show('login'),800)}catch(e){setupmsg.textContent=e.message}}
async function login(){loginmsg.textContent='Ingresando...';try{let j=await api('/v1/admin/login',{method:'POST',body:JSON.stringify({email:email.value.trim(),password:pass.value})});token=j.token;myEmail=j.email;sessionStorage.setItem('cgp_admin_token',token);sessionStorage.setItem('cgp_admin_email',myEmail);showPanel()}catch(e){loginmsg.textContent=e.message}}
function showPanel(){show('panel');who.textContent=myEmail;refresh();clearInterval(timer);timer=setInterval(()=>{if(!clients.classList.contains('hidden'))refreshClients()},5000)}function logout(){token='';myEmail='';sessionStorage.removeItem('cgp_admin_token');sessionStorage.removeItem('cgp_admin_email');clearInterval(timer);location.reload()}
function tab(which){let a=which==='clients';clients.classList.toggle('hidden',!a);admins.classList.toggle('hidden',a);tabclients.classList.toggle('active',a);tabadmins.classList.toggle('active',!a);if(a)refreshClients();else refreshAdmins()}async function refresh(){if(!clients.classList.contains('hidden'))return refreshClients();return refreshAdmins()}
async function refreshClients(){try{let j=await api('/v1/admin/requests');rows.innerHTML='';for(let q of j.requests){let tr=document.createElement('tr');let cls=esc(q.status);tr.innerHTML='<td>'+esc(q.name)+'</td><td>'+esc(q.email)+'</td><td title="'+esc(q.machine)+'">'+esc(q.machine_code)+'</td><td class="'+cls+'">'+esc(q.status)+'</td><td>'+fmt(q.created)+'</td><td>'+fmt(q.last_seen)+'</td><td>'+(q.expires?fmt(q.expires):'-')+'</td><td><div class="row"><button class="ok" data-a="approve">APROBAR</button><button data-a="reject">RECHAZAR</button><button class="danger" data-a="revoke">REVOCAR</button></div></td>';for(let bt of tr.querySelectorAll('button'))bt.onclick=()=>decision(q.id,bt.dataset.a);rows.appendChild(tr)}msg.textContent=''}catch(e){msg.textContent=e.message;if(String(e.message).includes('Sesión'))logout()}}
async function decision(id,action){let d=parseInt(days.value||'0',10);if(action==='revoke'&&!confirm('¿Revocar esta licencia?'))return;try{await api('/v1/admin/decision',{method:'POST',body:JSON.stringify({id,action,days:d,note:''})});await refreshClients()}catch(e){msg.textContent=e.message}}
async function refreshAdmins(){try{let j=await api('/v1/admin/admins');adminlist.innerHTML='';for(let a of j.admins){let d=document.createElement('div');d.className='adminitem';d.innerHTML='<span>'+esc(a.email)+'</span><button class="danger">ELIMINAR</button>';d.querySelector('button').onclick=()=>deleteAdmin(a.email);adminlist.appendChild(d)}msg.textContent='Administradores: '+j.admins.length+' / 5'}catch(e){msg.textContent=e.message}}
async function addAdmin(){try{await api('/v1/admin/admins',{method:'POST',body:JSON.stringify({email:newadminemail.value.trim(),password:newadminpass.value})});newadminemail.value='';newadminpass.value='';await refreshAdmins()}catch(e){msg.textContent=e.message}}
async function deleteAdmin(e){if(!confirm('¿Eliminar el administrador '+e+'?'))return;try{await api('/v1/admin/admins/delete',{method:'POST',body:JSON.stringify({email:e})});if(e.toLowerCase()===myEmail.toLowerCase()){logout();return}await refreshAdmins()}catch(err){msg.textContent=err.message}}
async function changePassword(){try{await api('/v1/admin/password',{method:'POST',body:JSON.stringify({current_password:curpass.value,new_password:newpass.value})});curpass.value='';newpass.value='';msg.textContent='Contraseña actualizada'}catch(e){msg.textContent=e.message}}
pass.addEventListener('keydown',e=>{if(e.key==='Enter')login()});init();
</script></body></html>`
